# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
repo_name: "robotics-arxiv-daily"
show_authors: True
show_links: True
show_badge: False
max_results: 2  # 测试时使用较小的值

publish_readme: True
publish_gitpage: False  # 测试时关闭
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search - 测试时只使用一个关键词
keywords:
    "Manipulation":
        filters: ["Robot Manipulation"]

