title: Robotics Arxiv Daily
description: Automatically Update Robotics Papers Daily using Github Actions (Update Every 8th hours)
show_downloads: true

## add remote theme
remote_theme: jekyll/minima@v2.5.1

# minima:
skin: dark

plugins:
 - jekyll-remote-theme # add this line to the plugins list if you already have one
 - jekyll-feed
 - jekyll-seo-tag
